import "./globals.css";


export const metadata = {
  title: "Projects",
  description: "Generated by create next app",
};

export default function ProjectLayout({ children }) {
  return <section>{children}</section>
}

